<?php

namespace Question;

use Laminas\Form\Element\Select;


$form = $this->form;
$form->setAttribute('action', $this->url('question', ['action' => 'index']));
$form->prepare();
echo $this->form()->openTag($form);

foreach ($this->questions as $question) {
    $form->add([
        'type' => Select::class,
        'name' => "question_".$question->getId(),
        'options' => [
            'label' => $question->getQuestion(),
            'value_options' => [
                '1' => $question->getFirstChoose(),
                '2' => $question->getSecondChoose(),
                '3' => $question->getThirdChoose()
            ],
        ],
    ]);

    $form->add([
        'name' => "correct_answer_".$question->getId(),
        'type' => 'hidden',
        'attributes' => [
                'value' => $question->getCorrectAnswer(),
        ]
    ]);
}

$correction = $this->correction;
$result = "";
$feedback = 0;
?>

<?php foreach ($this->questions as $question): ?>
    <?php
        $question_num = 'question_'.$question->getId();
        $correct_answer_num = 'correct_answer_'.$question->getId();
        if (isset($correction->submit) && $correction->$question_num == $correction->$correct_answer_num) {
            $result = "it is correct answer congratulation";
            $feedback = 1;
        } elseif (isset($correction->submit)) {
            $result = "oh! sorry you mis it!";
            $feedback = 0;
        }
    ?>
    <?= $this->formLabel($form->get("question_".$question->getId())); ?>
    <?= $this->formSelect($form->get("question_".$question->getId())); ?>
    <p <?= ($feedback == 0)? 'style="color: red"': 'style="color: green"'?>><?= $result?></p>
    <?= $this->formHidden($form->get("correct_answer_".$question->getId())); ?>
    <br>
<?php endforeach; ?>

<?php
echo $this->formSubmit($form->get('submit'));
?>


