<?php
var_dump($this->result);

$form = $this->form;
$form->setAttribute('action', $this->url('user', ['action' => 'login']));

$user_name = $form->get('user_name');
$user_name->setAttribute('class', 'form-control');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');


$submit = $form->get('submit');

$form->prepare();
echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formRow($user_name); ?>
        <?= $this->formRow($password); ?>
        <?= $this->formRow($submit); ?>
    </div>
<?php
echo $this->form()->closeTag(); ?>